### PR TITLE
Fix crypto TypeError Data must be a string or a buffer

### PR DESCRIPTION
**Pull request by filipemeneses**
I was having issues using this bot in my project, since it automatically parses JSON requests, crpyto was receiving an object instead a string, thus causing this error.

### CODE REVIEW

**Comment by ItamarM** [comment]
Hi @filipemeneses. Unfortunately, we can't accept this pull request.
1) The change replace the message instance on the validateMessage method. This breaks the atomic purpose of the method (validation).
2) Our framework/documentation specifically ask for 'string' object. It might break other bots who use this.

Our suggestion is that you will wrap our module with your custom translation code. (JSON->String and vice versa).

**Comment by filipemeneses** [comment]
@ItamarM Oh, okay. Just a few considerations: 

1. We could add a new private method for parsing response type.
2. It would tranform to string only if the response was an object, in this way, it would work in expressJS projects with default JSON parsing and those without it.

I've re-implemented the bot as an ES6 version, thanks for the suggestion! Loved how you guys designed it.

**Comment by fatmatto** [comment]
Hello, just wanted to add my experience with viber node here about this issue.

While it was amazingly easy to start with it took some coding to make it work with express and loopback.

With express you just need to setup a middleware BEFORE calling bodyparser middleware in which you store the raw request body into the request (let's say a _rawBody property)
Then before the viber webhook route, you swap the body with the raw request.

With loopback you do the same, but you need to register a loopback middleware in the parse:before phase., this middleware has the same role as the one in express. Then, you swap the request body content with the _rawBody.

Hope it helps :)

**Comment by Kraigo** [comment]
@fatmatto Thanks for solution! Works for me

**Comment by skyfall174** [comment]
@ItamarM Please add this information to readme.md I waste 2 hours to find this solution.

> Hello, just wanted to add my experience with viber node here about this issue.
> 
> While it was amazingly easy to start with it took some coding to make it work with express and loopback.
> 
> With express you just need to setup a middleware BEFORE calling bodyparser middleware in which you store the raw request body into the request (let's say a _rawBody property)
> Then before the viber webhook route, you swap the body with the raw request.
> 
> With loopback you do the same, but you need to register a loopback middleware in the parse:before phase., this middleware has the same role as the one in express. Then, you swap the request body content with the _rawBody.
> 
> Hope it helps :)

**Comment by ItamarM** [comment]
Hi @skyfall174 
I can't update the README as I no longer the maintainer of this repository. 
Let's keep this issue open so others will not waste their time!

**Pull request closed without merging**
